# Logistic Regression 5.a


In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
X_train=np.array([[0.346,0.303,0.358,0.602,0.790,0.611],
                 [0.780,0.439,0.729,0.863,0.753,0.965]])
Y_train=np.array([0,0,0,1,1,1])
X_test=np.array([[0.959,0.750,0.395,0.823,0.761,0.844],
                [0.382,0.306,0.760,0.764,0.874,0.435]])
Y_test=np.array([0,0,0,1,1,1])

In [3]:
Y_train = Y_train.reshape(1, X_train.shape[1])
Y_test = Y_test.reshape(1, X_test.shape[1])

In [4]:
print("Shape of X_train : ", X_train.shape)
print("Shape of Y_train : ", Y_train.shape)
print("Shape of X_test : ", X_test.shape)
print("Shape of Y_test : ", Y_test.shape)

Shape of X_train :  (2, 6)
Shape of Y_train :  (1, 6)
Shape of X_test :  (2, 6)
Shape of Y_test :  (1, 6)


In [5]:
#Logistic Function
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [6]:
def model(X, Y, learning_rate, iterations): 
    m = X_train.shape[1]
    n = X_train.shape[0]
    W = np.zeros((n,1))
    B = 0
    cross_entropy_list = []
    
    for i in range(iterations):
        Z = np.dot(W.T, X) + B
        A = sigmoid(Z)
        
        # cross entropy error function
        cross = -(1/m)*np.sum( Y*np.log(A) + (1-Y)*np.log(1-A))
        
        # Gradient Descent
        dW = (1/m)*np.dot(A-Y, X.T)
        dB = (1/m)*np.sum(A - Y)
        
        W = W - learning_rate*dW.T
        B = B - learning_rate*dB
        
        # Keeping track of our cross entropy error function value
        cross_entropy_list.append(cross)
        
        if(i%(iterations/10) == 0):
            print("cross entropy after ", i, "iteration is : ", cross)
        
    return W, B, cross_entropy_list

In [7]:
iterations = 1000000
learning_rate = 0.002
W, B, cross_entropy_list = model(X_train, Y_train, learning_rate = learning_rate, iterations = iterations)
print(W,B)

cross entropy after  0 iteration is :  0.6931471805599452
cross entropy after  100000 iteration is :  0.23233404841365107
cross entropy after  200000 iteration is :  0.13887902254686124
cross entropy after  300000 iteration is :  0.09954744745129197
cross entropy after  400000 iteration is :  0.07777286576914884
cross entropy after  500000 iteration is :  0.06390031784807679
cross entropy after  600000 iteration is :  0.054270905912205694
cross entropy after  700000 iteration is :  0.047187875007339716
cross entropy after  800000 iteration is :  0.04175497056462178
cross entropy after  900000 iteration is :  0.03745342486959348
[[20.36695928]
 [ 5.31915174]] -14.104892873419047


In [8]:
print(W,B)

[[20.36695928]
 [ 5.31915174]] -14.104892873419047


In [9]:
def accuracy(X, Y, W, B):    
    Z = np.dot(W.T, X) + B
    A = sigmoid(Z)
    A = A > 0.5   
    A = np.array(A, dtype = 'int64')
    acc = (1 - np.sum(np.absolute(A - Y))/Y.shape[1])*100
    print("Accuracy of the model is : ", round(acc, 1), "%")

In [10]:
accuracy(X_test, Y_test, W, B)

Accuracy of the model is :  66.7 %


# Logistic Regression 5.b

In [37]:
def model1(X, Y, learning_rate, iterations): 
    m = X_train.shape[1]
    n = X_train.shape[0]
    W1 = np.array([1.5,0.5])
    B1 = -1
    cross_entropy_list1 = []
    
    for i in range(iterations):
        Z = np.dot(W1.T, X) + B1
        A = sigmoid(Z)
        
        # cross entropy error function
        cross = -(1/m)*np.sum( Y*np.log(A) + (1-Y)*np.log(1-A))
        
        # Gradient Descent
        dW1 = (1/m)*np.dot(A-Y, X.T)
        dB1 = (1/m)*np.sum(A - Y)
        
        W1 = W1 - learning_rate*dW1.T
        B1 = B1 - learning_rate*dB1
        
        # Keeping track of our cross entropy error function value
        cross_entropy_list1.append(cross)
        
        if(i%(iterations/10) == 0):
            print("cross entropy after ", i, "iteration is : ", cross)
        
    return W, B, cross_entropy_list1

In [43]:
iterations = 10000000
learning_rate = 0.1
W1, B1, cross_entropy_list1 = model1(X_train, Y_train, learning_rate = learning_rate, iterations = iterations)


cross entropy after  0 iteration is :  0.5569500797547651
cross entropy after  1000000 iteration is :  0.0012948443736050602
cross entropy after  2000000 iteration is :  0.0006515830313335168
cross entropy after  3000000 iteration is :  0.00043575918420747563
cross entropy after  4000000 iteration is :  0.00032747982776236786
cross entropy after  5000000 iteration is :  0.00026236585863216236
cross entropy after  6000000 iteration is :  0.00021888453474993907
cross entropy after  7000000 iteration is :  0.00018778608046941066
cross entropy after  8000000 iteration is :  0.00016443750204114848
cross entropy after  9000000 iteration is :  0.00014626131700107336


In [44]:
print(W1,B1)

[[20.36695928]
 [ 5.31915174]] [[1 1 1 1 1 1]]


In [45]:
def accuracy(X, Y, W1, B1):    
    Z = np.dot(W1.T, X) + B1
    A = sigmoid(Z)
    A = A > 0.5   
    A = np.array(A, dtype = 'int64')
    acc = (1 - np.sum(np.absolute(A - Y))/Y.shape[1])*100
    print("Accuracy of the model is : ", round(acc, 1), "%")

In [46]:
def predict(X, W1, B1):    
    Z1 = []
    Z = np.dot(W1.T, X) + B1
   
    
    A = sigmoid(Z)
    A = A > 0.5   
    A = np.array(A, dtype = 'int64')
    return A


In [49]:
accuracy(X_test, Y_test, W1, B1)
B=predict(X_test, W1, B1)
print(B)

Accuracy of the model is :  50.0 %
[[1 1 1 1 1 1]]


In [48]:
from sklearn.metrics import precision_recall_fscore_support
precision_recall_fscore_support(Y_test, B, average='macro')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


(0.5, 0.5, 0.5, None)