# 4.a

In [103]:
#Importing required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error

In [104]:
#Importing training data and removing the unwanted column1
train_data = pd.read_csv('traindata.csv')
train_data1=train_data.drop('Column1',axis=1)
print(train_data1)

      Column2   Column3   Column4
0           6  0.341092 -4.528937
1           5  0.444131 -5.496812
2           4  0.231002 -2.886750
3           7  0.200275 -3.534375
4           3  0.291936 -4.352062
...       ...       ...       ...
7286        3  0.296178 -2.558250
7287        3  0.252795 -3.110500
7288        3  0.393705 -2.921187
7289        0  0.597590 -2.258062
7290        1  0.276221 -0.916250

[7291 rows x 3 columns]


In [105]:
#Checking out the data
print(train_data1.shape) 
train_data1.head(5)

(7291, 3)


Column2   Column3   Column4
0        6  0.341092 -4.528937
1        5  0.444131 -5.496812
2        4  0.231002 -2.886750
3        7  0.200275 -3.534375
4        3  0.291936 -4.352062

In [106]:
#Segrerating only the rows with 1 and 5
df_rows = train_data1[ (train_data1.Column2 == 1) | (train_data1.Column2 == 5)]
print(df_rows.shape)
df_rows.head(5)

(1561, 3)


Column2   Column3   Column4
1         5  0.444131 -5.496812
7         1  0.123043 -0.707875
9         1  0.113859 -0.931375
12        1  0.115371 -0.386000
13        1  0.102281 -0.378812

In [107]:
#Seperating Column2 which is label and Column3 and 4 which are features
x=df_rows.drop('Column2',axis=1)
y=df_rows['Column2']

In [108]:
#Training the algorithm using Linear kernel
svcclassifier=SVC(kernel='linear')
svcclassifier.fit(x,y)

SVC(kernel='linear')

In [109]:
#Importing test data
test_data = pd.read_csv('testdata.csv')
test_data1=test_data.drop('Column1',axis=1)
df_rows1 = test_data1[ (test_data1.Column2 == 1) | (test_data1.Column2 == 5)]
a=df_rows1.drop('Column2',axis=1)
b=df_rows1['Column2']

In [110]:
#Predicting the classes
y_predict=svcclassifier.predict(a)


In [112]:
#Evaluating the model
print(classification_report(b,y_predict))    #Accuracy is given
svcclassifier.n_support_                     #No.of support vectors

              precision    recall  f1-score   support

           1       1.00      0.97      0.98       264
           5       0.95      1.00      0.97       160

    accuracy                           0.98       424
   macro avg       0.97      0.98      0.98       424
weighted avg       0.98      0.98      0.98       424



array([14, 14])

# 4.b

In [113]:
train_first50 = df_rows.iloc[:50]
x=train_first50.drop('Column2',axis=1)
y=train_first50['Column2']
svcclassifier=SVC(kernel='linear')
svcclassifier.fit(x,y)
y_predict=svcclassifier.predict(a)



In [114]:
print(classification_report(b,y_predict))    #Accuracy with first 50 training points only
svcclassifier.n_support_                     #No.of Support Vectors


              precision    recall  f1-score   support

           1       1.00      0.97      0.98       264
           5       0.95      1.00      0.98       160

    accuracy                           0.98       424
   macro avg       0.98      0.98      0.98       424
weighted avg       0.98      0.98      0.98       424



array([1, 1])

In [94]:
train_first100 = df_rows.iloc[:100]
x=train_first100.drop('Column2',axis=1)
y=train_first100['Column2']
svcclassifier=SVC(kernel='linear')
svcclassifier.fit(x,y)
y_predict=svcclassifier.predict(a)


In [95]:
print(classification_report(b,y_predict))     #Accuracy with first 100 training points only
svcclassifier.n_support_                      #No.of Support Vectors


              precision    recall  f1-score   support

           1       1.00      0.97      0.98       264
           5       0.95      1.00      0.98       160

    accuracy                           0.98       424
   macro avg       0.98      0.98      0.98       424
weighted avg       0.98      0.98      0.98       424



array([2, 2])

In [96]:
train_first200 = df_rows.iloc[:200]
x=train_first200.drop('Column2',axis=1)
y=train_first200['Column2']
svcclassifier=SVC(kernel='linear')
svcclassifier.fit(x,y)
y_predict=svcclassifier.predict(a)


In [97]:
print(classification_report(b,y_predict))         #Accuracy with first 200 training points only
svcclassifier.n_support_                          #No.of Support Vectors

              precision    recall  f1-score   support

           1       1.00      0.97      0.98       264
           5       0.95      1.00      0.98       160

    accuracy                           0.98       424
   macro avg       0.98      0.98      0.98       424
weighted avg       0.98      0.98      0.98       424



array([4, 4])

In [98]:
train_first800 = df_rows.iloc[:800]
x=train_first800.drop('Column2',axis=1)
y=train_first800['Column2']
svcclassifier=SVC(kernel='linear')
svcclassifier.fit(x,y)
y_predict=svcclassifier.predict(a)


In [99]:
print(classification_report(b,y_predict))     #Accuracy with first 800 training points only 
svcclassifier.n_support_                      #No.of Support Vectors

              precision    recall  f1-score   support

           1       1.00      0.97      0.98       264
           5       0.95      1.00      0.98       160

    accuracy                           0.98       424
   macro avg       0.98      0.98      0.98       424
weighted avg       0.98      0.98      0.98       424



array([7, 7])

# Done for random 50 data points

In [127]:

train_sample50 = df_rows.sample(n=50)
x=train_sample50.drop('Column2',axis=1)
y=train_sample50['Column2']
svcclassifier=SVC(kernel='linear')
svcclassifier.fit(x,y)
y_predict=svcclassifier.predict(a)


In [128]:
print(classification_report(b,y_predict))      #Accuracy for random 50 points
svcclassifier.n_support_                       #No.of Support Vectors

              precision    recall  f1-score   support

           1       1.00      0.96      0.98       264
           5       0.94      1.00      0.97       160

    accuracy                           0.97       424
   macro avg       0.97      0.98      0.97       424
weighted avg       0.98      0.97      0.97       424



array([2, 2])

# 4.d

In [132]:
c=[0.01,1,100,10000,1000000]
for C in c:
    print(C)
    rbfclassifier=SVC(kernel='rbf',C=C)
    print(1-rbfclassifier.fit(x,y).score(x,y))
    y_pre=rbfclassifier.predict(a)
    print(1-rbfclassifier.score(a,b))
    


0.01
0.36
0.37735849056603776
1
0.0
0.02358490566037741
100
0.0
0.02594339622641506
10000
0.0
0.02594339622641506
1000000
0.0
0.02594339622641506


# 4. c
   

# i

In [41]:
polyclassifier = SVC(kernel='poly', degree=2,C=0.0001)
polyclassifier.fit(x,y)
y_predictpoly=polyclassifier.predict(a)
print(1-polyclassifier.fit(x,y).score(x,y))                        #Training error for Q=2
polyclassifier = SVC(kernel='poly', degree=5,C=0.0001)
polyclassifier.fit(x,y)
y_predictpoly=polyclassifier.predict(a)
print(1-polyclassifier.fit(x,y).score(x,y))                        #Training error for Q=5

0.42000000000000004
0.31999999999999995


# ii

In [39]:
polyclassifier = SVC(kernel='poly', degree=2,C=0.001)
polyclassifier.fit(x,y)
y_predictpoly=polyclassifier.predict(a)
print(polyclassifier.n_support_)                            
polyclassifier = SVC(kernel='poly', degree=5,C=0.001)
polyclassifier.fit(x,y)
y_predictpoly=polyclassifier.predict(a)
print(polyclassifier.n_support_)                                   


[21 21]
[12 12]


# iii

In [40]:
polyclassifier = SVC(kernel='poly', degree=2,C=0.01)
polyclassifier.fit(x,y)
y_predictpoly=polyclassifier.predict(a)
print(1-polyclassifier.fit(x,y).score(x,y))          #Training error at Q=2
polyclassifier = SVC(kernel='poly', degree=5,C=0.01)
polyclassifier.fit(x,y)
y_predictpoly=polyclassifier.predict(a)
print(1-polyclassifier.fit(x,y).score(x,y))           #Training error at Q=5

0.06000000000000005
0.040000000000000036


# iv 

In [131]:
polyclassifier = SVC(kernel='poly', degree=2,C=1)
polyclassifier.fit(x,y)
y_predictpoly=polyclassifier.predict(a)
print(1-polyclassifier.score(a,b))                    #Test error at Q=2
polyclassifier = SVC(kernel='poly', degree=5,C=1)
polyclassifier.fit(x,y)
y_predictpoly=polyclassifier.predict(a)
print(1-polyclassifier.score(a,b))                    #Test error at Q=5

0.02358490566037741
0.018867924528301883
